version: 2
project_name: metana

release:
  prerelease: auto
  draft: true
  name_template: Metana {{ .Version }}
  github:
    owner: g14a
    name: metana

builds:
  - env: [CGO_ENABLED=0]
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

brews:
  - name: metana
    homepage: https://github.com/g14a/metana
    description: An abstract migration tool written in Go for Go services.
    license: "Apache-2.0"
    repository:
      owner: g14a
      name: homebrew-metana
      branch: main
    directory: Formula
    install: |
      bin.install "metana"
    test: |
      system "#{bin}/metana", "--help"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

nfpms:
  - maintainer: Gowtham Munukutla <gowtham.m81197@gmail.com>
    description: Abstract task migration tool written in Go for Golang services. Database and non database migration management brought to your CLI.
    homepage: https://github.com/g14a/metana
    license: Apache License 2.0
    formats:
      - deb
      - rpm
      - apk
      - termux.deb
      - archlinux